[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "matplotlib-rosepine"
version = "0.2.0"
description = "Rosé Pine matplotlib styles"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Christian Samuel Ramirez", email = "chrisram0403@proton.me" }]
keywords = ["matplotlib", "rose-pine", "theme", "style", "plotting"]
dependencies = ["matplotlib>=3.6"]

[project.optional-dependencies]
labels = [
    "adjusttext>=1.4.0",
]

[dependency-groups]
dev = [
    "adjusttext>=1.4.0",
    "numpy",
    "pytest>=8.4.2",
]

[tool.hatch.build.targets.wheel]
packages = ["src/matplotlib_rosepine"]
