"""Derive template.mplstyle from the stock matplotlib rc file.

Copies the default rc verbatim, then uncomments and rewrites the
theme-relevant keys as Rosé Pine Bloom ``$role`` variables (colors) or
fixed project values. Feed the result to rose-pine-bloom to emit one
style per variant. Re-run after upgrading matplotlib to refresh the
template while preserving new upstream comments and defaults.
"""

import re
from pathlib import Path

import matplotlib

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "template.mplstyle"
STYLES = ROOT / "src" / "matplotlib_rosepine" / "styles"

# Color keys -> Rosé Pine role. Plain values become "#$role"; the rc
# comment-stripper only honors double quotes, so the '#' must sit inside
# them (bloom runs with -f hex-ns, emitting bare hex).
COLOR_TOKENS = {
    "figure.facecolor": "base",
    "figure.edgecolor": "base",
    "savefig.facecolor": "base",
    "savefig.edgecolor": "base",
    "axes.facecolor": "base",
    "axes.edgecolor": "muted",
    "axes.labelcolor": "text",
    "axes.titlecolor": "text",
    "text.color": "text",
    "patch.edgecolor": "text",
    "xtick.color": "subtle",
    "ytick.color": "subtle",
    "xtick.labelcolor": "text",
    "ytick.labelcolor": "text",
    "grid.color": "overlay",
    "legend.facecolor": "base",
    "legend.edgecolor": "muted",
    "legend.labelcolor": "text",
    "boxplot.flierprops.color": "text",
    "boxplot.flierprops.markeredgecolor": "text",
    "boxplot.boxprops.color": "text",
    "boxplot.whiskerprops.color": "text",
    "boxplot.capprops.color": "text",
    "boxplot.medianprops.color": "love",
    "boxplot.meanprops.color": "foam",
    "boxplot.meanprops.markerfacecolor": "foam",
    "boxplot.meanprops.markeredgecolor": "foam",
}

# axes.prop_cycle accent order. Single-quoted, no '#', per the rc format.
CYCLE = ("love", "gold", "pine", "foam", "iris", "rose")

# Non-color keys pinned to project values.
FIXED_VALUES = {
    "figure.dpi": "300",
    "font.family": "sans-serif",
    "font.sans-serif": "Anthropic Sans Text, Google Sans Flex, Arimo, Arial, DejaVu Sans",
    "svg.fonttype": "none",
    "figure.constrained_layout.use": "True",
    "axes.spines.top": "False",
    "axes.spines.right": "False",
    "xtick.direction": "in",
    "ytick.direction": "in",
    "axes.prop_cycle": "cycler('color', [%s])" % ", ".join(f"'${r}'" for r in CYCLE),
}

LINE = re.compile(
    r"^#?(?P<key>[\w.-]+)(?P<sep>\s*:\s*)(?P<val>.*?)(?P<comment>\s+#.*)?$"
)


def rewrite(line):
    """Return the templated form of one rc line, or the line unchanged."""
    m = LINE.match(line)
    if not m:
        return line
    key = m["key"]
    comment = m["comment"] or ""
    if key in COLOR_TOKENS:
        value = f'"#${COLOR_TOKENS[key]}"'
    elif key in FIXED_VALUES:
        value = FIXED_VALUES[key]
    else:
        return line
    return f"{key}{m['sep']}{value}{comment}\n"


def main():
    src = matplotlib.matplotlib_fname()
    header = (
        "## Rosé Pine Bloom template for matplotlib.\n"
        "## Generated by scripts/build_template.py from matplotlib's default rc.\n"
        f"## Fill with: rose-pine-bloom -t {TEMPLATE.name} -o {STYLES.relative_to(ROOT)} -f hex-ns\n\n"
    )
    with open(src) as f:
        body = "".join(rewrite(line) for line in f)
    TEMPLATE.write_text(header + body)

    missing = [
        key
        for key in {**COLOR_TOKENS, **FIXED_VALUES}
        if not re.search(rf"^{re.escape(key)}\s*:", body, re.M)
    ]
    if missing:
        raise SystemExit(f"template left keys unset: {missing}")
    print(f"wrote {TEMPLATE}")


if __name__ == "__main__":
    main()
